title: my tech
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://kyoon55.github.io/my-tech/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/kyoon55/my-tech